; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24210.0 

	TITLE	F:\playground\assassin-playground\ctsvetkov\minh_nguyen\zlibCompression\zlib-1.2.8\inffast.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
